using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Tessera.Generator
{
    /// <summary>
    /// Emits the C++ view headers: one header per model type, in a folder per C++ namespace
    /// (<c>game/Monster.tessera.hpp</c>), plus an umbrella header that includes them all. A view header has two guarded
    /// sections: the class (accessor declarations only, so it reads like an interface, and needs only forward
    /// declarations of other views), then its layout table and one-line accessor definitions (which include the other
    /// views' headers). That order makes mutually referencing models work. Guards carry a hash of the header's content,
    /// so identical headers written by two model assemblies merge, and two different versions of one type fail with a
    /// clear error.
    /// </summary>
    internal sealed class CppEmitter
    {
        private const string HashToken = "@TESSERA_HASH@";
        private readonly List<TypeModel> _types;
        private readonly List<EnumModel> _enums;
        private readonly Settings _settings;
        private readonly string _assembly;
        private CodeWriter _w = new CodeWriter();

        public CppEmitter(List<TypeModel> types, List<EnumModel> enums, Settings settings, string assembly)
        {
            _types = types;
            _enums = enums;
            _settings = settings;
            _assembly = assembly;
        }

        /// <summary>(relative path, content) of every header; the umbrella header is last.</summary>
        public List<KeyValuePair<string, string>> EmitFiles(string umbrellaName)
        {
            var objects = _types.OfType<ObjectModel>().Where(o => o.Map == null).ToList();
            var maps = _types.OfType<ObjectModel>().Where(o => o.Map != null).ToList();
            var structs = OrderStructs(_types.OfType<StructModel>().ToList());
            var unions = _types.OfType<UnionModel>().ToList();
            var files = new List<KeyValuePair<string, string>>();
            foreach (var e in _enums.OrderBy(x => x.CsName, StringComparer.Ordinal)) files.Add(EnumFile(e));
            foreach (var s in structs) files.Add(StructFile(s));
            foreach (var o in objects) files.Add(ObjectFile(o));
            foreach (var m in maps) files.Add(MapFile(m));
            foreach (var u in unions) files.Add(UnionFile(u));
            files.Add(new KeyValuePair<string, string>(umbrellaName, Umbrella(objects, files)));
            return files;
        }

        private string Umbrella(List<ObjectModel> objects, List<KeyValuePair<string, string>> files)
        {
            _w = new CodeWriter();
            _w.Line("// <auto-generated>");
            _w.Line($"//   Tessera C++ views for the C# assembly '{_assembly}': includes the header of every model type.");
            _w.Line("//   Generated by Tessera.Generator from the C# models; edit the models, not these files.");
            _w.Line("//   Each type also has its own header (<namespace>/<Type>.tessera.hpp) for including only what a file uses.");
            _w.Line("// </auto-generated>");
            _w.Line("//");
            var root = PickRoot(objects);
            if (root != null)
            {
                _w.Line("// Reading a buffer:");
                _w.Line($"//   tessera::Reader<{Qualified(root.Symbol, root.CppName)}> reader(data, size);  // verifies by default");
                _w.Line("//   if (!reader) { /* tessera::to_string(reader.error()) */ }");
                _w.Line($"//   auto {Naming.Member(root.CppName, CppNaming.SnakeCase)} = reader.root();");
            }

            _w.Line("#pragma once");
            _w.Line();
            foreach (var f in files.Select(f => f.Key).OrderBy(x => x, StringComparer.Ordinal)) _w.Line($"#include \"{f}\"");
            return _w.ToString();
        }

        // ------------------------------------------------------------------ files

        private static string Path(string ns, string cppName) => ns.Replace("::", "/") + "/" + cppName + ".tessera.hpp";

        private string PathOf(ISymbol symbol, string cppName) => Path(Namespace(symbol), cppName);

        private string GuardOf(ISymbol symbol, string cppName) => (Namespace(symbol) + "_" + cppName).Replace("::", "_");

        /// <summary>Include path of <paramref name="to"/> relative to the folder of <paramref name="from"/>.</summary>
        private static string Relative(string from, string to)
        {
            string[] a = from.Split('/'), b = to.Split('/');
            int common = 0;
            while (common < a.Length - 1 && common < b.Length - 1 && a[common] == b[common]) common++;
            var parts = new List<string>();
            for (int i = common; i < a.Length - 1; i++) parts.Add("..");
            for (int i = common; i < b.Length; i++) parts.Add(b[i]);
            return string.Join("/", parts);
        }

        private void Banner(string what)
        {
            _w.Line("// <auto-generated>");
            _w.Line($"//   Tessera C++ view of the C# {what}.");
            _w.Line("//   Generated by Tessera.Generator from the C# model; edit the model, not this file.");
            _w.Line("// </auto-generated>");
        }

        private void Includes(string from, IEnumerable<string> paths)
        {
            foreach (var p in paths.Where(p => p != from).Distinct().OrderBy(x => x, StringComparer.Ordinal)) _w.Line($"#include \"{Relative(from, p)}\"");
        }

        /// <summary>Replaces the hash token with a hash of the content, so identical headers get identical guards.</summary>
        private static KeyValuePair<string, string> Finish(string path, string content)
        {
            ulong hash = XxHash.Hash64(System.Text.Encoding.UTF8.GetBytes(content));
            return new KeyValuePair<string, string>(path, content.Replace(HashToken, hash.ToString("X16", CultureInfo.InvariantCulture)));
        }

        /// <summary>Guard that fails when another, different header already defined the same C++ type.</summary>
        private void TypeGuard(string kind, string guard, string qualified)
        {
            _w.Line($"#if defined(TESSERA_TYPE_{guard}) && !defined(TESSERA_{kind}_{guard}_{HashToken})");
            _w.Line($"#error \"Tessera: {qualified} is defined by headers from two different versions of its C# model\"");
            _w.Line("#endif");
            _w.Line($"#ifndef TESSERA_{kind}_{guard}_{HashToken}");
            _w.Line($"#define TESSERA_{kind}_{guard}_{HashToken}");
            _w.Line($"#define TESSERA_TYPE_{guard}");
        }

        private KeyValuePair<string, string> EnumFile(EnumModel e)
        {
            _w = new CodeWriter();
            string path = PathOf(e.Symbol, e.CppName);
            Banner($"{(e.IsFlags ? "[Flags] " : "")}enum {e.DisplayName}");
            TypeGuard("ENUM", GuardOf(e.Symbol, e.CppName), "::" + Namespace(e.Symbol) + "::" + e.CppName);
            _w.Line("#include <tessera/tessera.hpp>");
            OpenNamespace(e.Symbol);
            EmitEnum(e);
            CloseNamespace();
            _w.Line();
            _w.Line("#endif");
            return Finish(path, _w.ToString());
        }

        private KeyValuePair<string, string> StructFile(StructModel s)
        {
            _w = new CodeWriter();
            string path = PathOf(s.Symbol, s.CppName);
            Banner($"struct {s.DisplayName}");
            TypeGuard("STRUCT", GuardOf(s.Symbol, s.CppName), "::" + Namespace(s.Symbol) + "::" + s.CppName);
            _w.Line("#include <tessera/tessera.hpp>");
            Includes(path, s.Fields.Where(f => f.Enum != null).Select(f => PathOf(f.Enum!.Symbol, f.Enum.CppName))
                .Concat(s.Fields.Where(f => f.Struct != null).Select(f => PathOf(f.Struct!.Symbol, f.Struct.CppName))));
            OpenNamespace(s.Symbol);
            EmitStruct(s);
            CloseNamespace();
            _w.Line();
            _w.Open("namespace tessera");
            EmitStructSchema(s);
            _w.Close("  // namespace tessera");
            _w.Line();
            _w.Line("#endif");
            return Finish(path, _w.ToString());
        }

        /// <summary>Enums and structs a value needs complete, and the views it refers to.</summary>
        private static void Dependencies(ValueModel v, HashSet<EnumModel> enums, HashSet<StructModel> structs, HashSet<TypeModel> views)
        {
            if (v.Enum != null) enums.Add(v.Enum);
            if (v.Struct != null) structs.Add(v.Struct);
            if (v.Object != null)
            {
                views.Add(v.Object);
                if (v.Object.Map != null)
                {
                    // tessera::Map<K, V> names its key and value types.
                    Dependencies(v.Object.Map.Key, enums, structs, views);
                    Dependencies(v.Object.Map.Value, enums, structs, views);
                }
            }

            if (v.Union != null) views.Add(v.Union);
            if (v.Vector != null) Dependencies(v.Vector.Element, enums, structs, views);
        }

        private static bool IsMap(TypeModel t) => t is ObjectModel { Map: not null };

        private string ViewPath(TypeModel t) =>
            t is UnionModel u ? PathOf(u.Symbol, u.CppName) : IsMap(t) ? MapPath((ObjectModel)t) : PathOf(((ObjectModel)t).Symbol, t.CppName);

        private ISymbol ViewSymbol(TypeModel t) => t is UnionModel u ? u.Symbol : ((ObjectModel)t).Symbol;

        /// <summary>Leaves the last namespace open, so declarations in the class's own namespace share its block.</summary>
        private void ForwardDeclarations(IEnumerable<TypeModel> views)
        {
            foreach (var v in views.Where(v => !IsMap(v)).OrderBy(v => ViewPath(v), StringComparer.Ordinal))
            {
                OpenNamespace(ViewSymbol(v));
                _w.Line($"class {v.CppName};");
            }
        }

        private KeyValuePair<string, string> ObjectFile(ObjectModel o)
        {
            _w = new CodeWriter();
            string path = PathOf(o.Symbol, o.CppName);
            string guard = GuardOf(o.Symbol, o.CppName);
            var enums = new HashSet<EnumModel>();
            var structs = new HashSet<StructModel>();
            var views = new HashSet<TypeModel>();
            foreach (var m in o.Members) Dependencies(m.Value, enums, structs, views);
            views.Remove(o);

            Banner($"{Describe(o.Symbol)} {o.DisplayName}");
            TypeGuard("DECL", guard, "::" + Namespace(o.Symbol) + "::" + o.CppName);
            _w.Line("#include <tessera/tessera.hpp>");
            Includes(path, enums.Select(e => PathOf(e.Symbol, e.CppName)).Concat(structs.Select(s => PathOf(s.Symbol, s.CppName))));
            ForwardDeclarations(views);
            OpenNamespace(o.Symbol);
            EmitTableClass(o);
            CloseNamespace();
            _w.Line();
            _w.Line("#endif");
            _w.Line();
            _w.Line($"#ifndef TESSERA_DEFS_{guard}_{HashToken}");
            _w.Line($"#define TESSERA_DEFS_{guard}_{HashToken}");
            Includes(path, views.Select(ViewPath));
            _w.Line();
            _w.Open("namespace tessera");
            EmitTableSchema(o);
            _w.Close("  // namespace tessera");
            OpenNamespace(o.Symbol);
            EmitTableAccessors(o);
            CloseNamespace();
            _w.Line();
            _w.Line("#endif");
            return Finish(path, _w.ToString());
        }

        // ------------------------------------------------------------------ dictionaries

        /// <summary>The C++ type of a dictionary, fully qualified (identical in every assembly's headers).</summary>
        private string MapSpelling(ObjectModel m)
        {
            string? open = _openNs;
            var names = _memberNames;
            _openNs = null;
            _memberNames = null;
            string t = "::tessera::Map<" + VectorElementType(m.Map!.Key) + ", " + VectorElementType(m.Map.Value) + ">";
            _openNs = open;
            _memberNames = names;
            return t;
        }

        private string MapGuard(ObjectModel m) => "tessera_Map_" + XxHash.Hash64(System.Text.Encoding.UTF8.GetBytes(MapSpelling(m))).ToString("X16", CultureInfo.InvariantCulture);

        private string MapPath(ObjectModel m) => "tessera_maps/" + MapGuard(m).Substring("tessera_".Length) + ".tessera.hpp";

        /// <summary>The layout table of tessera::Map&lt;K, V&gt; (the view itself is part of the runtime).</summary>
        private KeyValuePair<string, string> MapFile(ObjectModel m)
        {
            _w = new CodeWriter();
            string path = MapPath(m);
            string spelling = MapSpelling(m);
            var enums = new HashSet<EnumModel>();
            var structs = new HashSet<StructModel>();
            var views = new HashSet<TypeModel>();
            Dependencies(m.Map!.Key, enums, structs, views);
            Dependencies(m.Map.Value, enums, structs, views);
            views.Remove(m);
            Banner($"dictionary {m.DisplayName}");
            TypeGuard("MAP", MapGuard(m), spelling);
            _w.Line("#include <tessera/tessera.hpp>");
            Includes(path, enums.Select(e => PathOf(e.Symbol, e.CppName)).Concat(structs.Select(s => PathOf(s.Symbol, s.CppName))).Concat(views.Select(ViewPath)));
            _w.Line();
            _w.Open("namespace tessera");
            EmitTableSchema(m, spelling);
            _w.Close("  // namespace tessera");
            _w.Line();
            _w.Line("#endif");
            return Finish(path, _w.ToString());
        }

        private KeyValuePair<string, string> UnionFile(UnionModel u)
        {
            _w = new CodeWriter();
            string path = PathOf(u.Symbol, u.CppName);
            string guard = GuardOf(u.Symbol, u.CppName);
            var members = u.Members.Select(m => (TypeModel)m.Type).ToList();

            Banner($"{Describe(u.Symbol)} {u.DisplayName} (union)");
            TypeGuard("DECL", guard, "::" + Namespace(u.Symbol) + "::" + u.CppName);
            _w.Line("#include <tessera/tessera.hpp>");
            ForwardDeclarations(members);
            OpenNamespace(u.Symbol);
            EmitUnionClass(u);
            CloseNamespace();
            _w.Line();
            _w.Line("#endif");
            _w.Line();
            _w.Line($"#ifndef TESSERA_DEFS_{guard}_{HashToken}");
            _w.Line($"#define TESSERA_DEFS_{guard}_{HashToken}");
            Includes(path, members.Select(ViewPath));
            _w.Line();
            _w.Open("namespace tessera");
            EmitUnionSchema(u);
            _w.Close("  // namespace tessera");
            OpenNamespace(u.Symbol);
            EmitUnionAccessors(u);
            CloseNamespace();
            _w.Line();
            _w.Line("#endif");
            return Finish(path, _w.ToString());
        }

        /// <summary>Example root for the usage comment: a type no other type references, with the most members.</summary>
        private static ObjectModel? PickRoot(List<ObjectModel> objects)
        {
            var referenced = new HashSet<TypeModel>();
            void Mark(ObjectModel owner, ValueModel v)
            {
                if (v.Object != null && v.Object != owner) referenced.Add(v.Object);
                if (v.Union != null) foreach (var m in v.Union.Members) if (m.Type != owner) referenced.Add(m.Type);
                if (v.Vector != null) Mark(owner, v.Vector.Element);
            }

            foreach (var o in objects) foreach (var m in o.Members) Mark(o, m.Value);
            return objects.Where(o => !referenced.Contains(o)).OrderByDescending(o => o.Members.Count).FirstOrDefault() ?? objects.FirstOrDefault();
        }

        // ------------------------------------------------------------------ namespaces

        private string? _openNs;

        private string Namespace(ISymbol symbol) => NamespaceOf(symbol, _settings, _assembly);

        /// <summary>C++ namespace of a model type: TesseraCppNamespace if set, else the lower-cased C# namespace.</summary>
        public static string NamespaceOf(ISymbol symbol, Settings settings, string assembly)
        {
            if (settings.Namespace != null) return settings.Namespace;
            var ns = symbol.ContainingNamespace;
            if (ns == null || ns.IsGlobalNamespace) return Naming.Sanitize(assembly.ToLowerInvariant().Replace('.', '_'));
            return string.Join("::", ns.ToDisplayString().Split('.').Select(p => Naming.Sanitize(p.ToLowerInvariant())));
        }

        private void OpenNamespace(ISymbol symbol)
        {
            string ns = Namespace(symbol);
            if (ns == _openNs) return;
            CloseNamespace();
            _w.Line();
            _w.Line($"namespace {ns} {{");
            _openNs = ns;
        }

        private void CloseNamespace()
        {
            if (_openNs == null) return;
            _w.Line();
            _w.Line($"}}  // namespace {_openNs}");
            _openNs = null;
        }

        // Inside the model's own namespace, types are named without qualification unless an accessor of the class being
        // emitted has the same name (possible with PascalCase/original accessor names).
        private HashSet<string>? _memberNames;

        private string Qualified(ISymbol symbol, string cppName)
        {
            string ns = Namespace(symbol);
            bool shortOk = _openNs == ns && (_memberNames == null || !_memberNames.Contains(cppName));
            return shortOk ? cppName : "::" + ns + "::" + cppName;
        }

        // ------------------------------------------------------------------ enums

        private void EmitEnum(EnumModel e)
        {
            _w.Line();
            _w.Line($"/// C# {(e.IsFlags ? "[Flags] " : "")}enum {e.DisplayName}");
            _w.Line($"enum class {e.CppName} : {ScalarType(e.Underlying)} {{");
            _w.Indent();
            var used = new HashSet<string>();
            foreach (var kv in e.Values)
            {
                string name = Naming.Sanitize(kv.Key);
                while (!used.Add(name)) name += "_";
                _w.Line($"{name} = {EnumLiteral(e.Underlying, kv.Value)},");
            }

            _w.Outdent();
            _w.Line("};");
            if (e.IsFlags)
            {
                string u = ScalarType(e.Underlying);
                string t = e.CppName;
                _w.Line($"constexpr {t} operator|({t} a, {t} b) noexcept {{ return static_cast<{t}>(static_cast<{u}>(a) | static_cast<{u}>(b)); }}");
                _w.Line($"constexpr {t} operator&({t} a, {t} b) noexcept {{ return static_cast<{t}>(static_cast<{u}>(a) & static_cast<{u}>(b)); }}");
                _w.Line($"constexpr {t} operator^({t} a, {t} b) noexcept {{ return static_cast<{t}>(static_cast<{u}>(a) ^ static_cast<{u}>(b)); }}");
                _w.Line($"constexpr {t} operator~({t} a) noexcept {{ return static_cast<{t}>(~static_cast<{u}>(a)); }}");
                _w.Line($"constexpr bool any({t} a) noexcept {{ return static_cast<{u}>(a) != 0; }}");
            }
        }

        private static string EnumLiteral(WireKind kind, object value)
        {
            switch (kind)
            {
                case WireKind.Int64:
                    long l = Convert.ToInt64(value, CultureInfo.InvariantCulture);
                    return l == long.MinValue ? "(-9223372036854775807ll - 1)" : l.ToString(CultureInfo.InvariantCulture) + "ll";
                case WireKind.UInt64:
                    return Convert.ToUInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture) + "ull";
                case WireKind.UInt32:
                    return Convert.ToUInt32(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture) + "u";
                case WireKind.Int32:
                    int i = Convert.ToInt32(value, CultureInfo.InvariantCulture);
                    return i == int.MinValue ? "(-2147483647 - 1)" : i.ToString(CultureInfo.InvariantCulture);
                default:
                    return Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
            }
        }

        // ------------------------------------------------------------------ structs

        private static List<StructModel> OrderStructs(List<StructModel> structs)
        {
            var ordered = new List<StructModel>();
            var done = new HashSet<StructModel>();
            void Visit(StructModel s)
            {
                if (!done.Add(s)) return;
                foreach (var f in s.Fields)
                {
                    if (f.Struct != null) Visit(f.Struct);
                }

                ordered.Add(s);
            }

            foreach (var s in structs) Visit(s);
            return ordered;
        }

        private void EmitStruct(StructModel s)
        {
            _w.Line();
            _w.Line($"/// C# struct {s.DisplayName} ({s.Size} bytes, stored {(s.SharedByDefault ? "once behind an offset" : "inline")})");
            _w.Line($"struct {s.CppName} {{");
            _w.Indent();
            int cursor = 0, pad = 0;
            foreach (var f in s.Fields)
            {
                if (f.Offset > cursor) _w.Line($"std::uint8_t tessera_pad{pad++}_[{f.Offset - cursor}];");
                _w.Line($"{StructFieldType(f)} {f.CppName};");
                cursor = f.Offset + f.Size;
            }

            if (s.Size > cursor) _w.Line($"std::uint8_t tessera_pad{pad}_[{s.Size - cursor}];");
            _w.Outdent();
            _w.Line("};");
            var checks = new List<string> { $"sizeof({s.CppName}) == {s.Size}", $"alignof({s.CppName}) == {s.Align}" };
            checks.AddRange(s.Fields.Select(f => $"offsetof({s.CppName}, {f.CppName}) == {f.Offset}"));
            _w.Line($"static_assert({string.Join(" && ", checks)}, \"layout must match the C# writer\");");
        }

        private string StructFieldType(StructField f)
        {
            if (f.Struct != null) return Qualified(f.Struct.Symbol, f.Struct.CppName);
            if (f.Enum != null) return Qualified(f.Enum.Symbol, f.Enum.CppName);
            return ScalarType(f.Kind);
        }

        private void EmitStructSchema(StructModel s)
        {
            string q = Qualified(s.Symbol, s.CppName);
            _w.Open($"template <> struct schema<{q}>");
            _w.Line($"static constexpr std::string_view name = {CppString(s.WireName)};");
            _w.Line($"static constexpr std::uint64_t fingerprint = 0x{s.Fingerprint:X16}ull;");
            _w.Line("static constexpr auto fields = std::make_tuple(");
            _w.Indent();
            for (int i = 0; i < s.Fields.Count; i++)
            {
                var f = s.Fields[i];
                _w.Line($"struct_field<{q}, {StructFieldType(f)}>{{{CppString(f.Name)}, &{q}::{f.CppName}}}{(i + 1 < s.Fields.Count ? "," : "")}");
            }

            _w.Outdent();
            _w.Line(");");
            _w.Close(";");
        }

        // ------------------------------------------------------------------ tables

        private void EmitTableClass(ObjectModel o)
        {
            _w.Line();
            _w.Line($"/// C# {Describe(o.Symbol)} {o.DisplayName}");
            _w.Line($"class {o.CppName} final : public tessera::Table<{o.CppName}> {{");
            _w.Line("public:");
            _w.Indent();
            _w.Line("using Table::Table;");
            _memberNames = new HashSet<string>(o.Members.Select(m => m.CppName).Concat(o.Members.Select(HasName)), StringComparer.Ordinal);
            if (o.Members.Count > 0) _w.Line();
            int width = o.Members.Count == 0 ? 0 : o.Members.Max(m => AccessorType(m.Value).Length);
            var declarations = o.Members.Select(m => $"{AccessorType(m.Value).PadRight(width)} {m.CppName}() const noexcept;").ToList();
            int declWidth = declarations.Count == 0 ? 0 : declarations.Max(d => d.Length);
            for (int i = 0; i < o.Members.Count; i++) _w.Line($"{declarations[i].PadRight(declWidth)}  // {MemberComment(o.Members[i])}");
            if (o.Members.Count > 0)
            {
                _w.Line();
                _w.Line("// Presence (false when the member was absent, null or equal to its default when written).");
                foreach (var m in o.Members) _w.Line($"bool {HasName(m)}() const noexcept;");
            }

            _memberNames = null;
            _w.Outdent();
            _w.Line("};");
        }

        private string HasName(MemberModel m)
        {
            switch (_settings.Naming)
            {
                case CppNaming.CamelCase: return "has" + char.ToUpperInvariant(m.CppName[0]) + m.CppName.Substring(1);
                case CppNaming.PascalCase:
                case CppNaming.Original: return "Has" + char.ToUpperInvariant(m.CppName[0]) + m.CppName.Substring(1);
                default: return "has_" + m.CppName;
            }
        }

        private void EmitTableSchema(ObjectModel o, string? spelling = null)
        {
            string q = spelling ?? Qualified(o.Symbol, o.CppName);
            _w.Line();
            _w.Open($"template <> struct schema<{q}>");
            _w.Line($"static constexpr std::string_view name = {CppString(o.WireName)};");
            _w.Line($"static constexpr std::uint64_t fingerprint = 0x{o.Fingerprint:X16}ull;");
            _w.Line($"static constexpr std::uint64_t deep_fingerprint = 0x{o.DeepFingerprint:X16}ull;");
            _w.Line($"static constexpr std::uint32_t words = {o.HeaderWords};");
            _w.Line($"static constexpr std::uint32_t fixed = {o.FixedSize};");
            _w.Line($"static constexpr std::uint16_t cells[] = {{{string.Join(", ", o.Cells.Select(c => c.CellSize.ToString(CultureInfo.InvariantCulture)).Concat(new[] { "0" }))}}};");
            var ordered = LayoutBuilder.WireOrder(o).ToList();
            if (ordered.Count == 0)
            {
                _w.Line("static constexpr std::tuple<> fields{};");
            }
            else
            {
                _w.Line("static constexpr auto fields = std::make_tuple(");
                _w.Indent();
                int width = ordered.Max(m => FieldType(m.Value).Length);
                for (int i = 0; i < ordered.Count; i++)
                {
                    var m = ordered[i];
                    string def = DefaultLiteral(m);
                    string tail = def.Length > 0 ? ", " + def : "";
                    string type = ("field<" + FieldType(m.Value) + ">").PadRight(width + 7);
                    string bit = m.IsFixed ? $"tessera::fixed_at({m.FixedOffset})" : m.Bit.ToString(CultureInfo.InvariantCulture);
                    _w.Line($"{type}{{{CppString(m.WireName)}, 0x{m.NameHash:X16}ull, {bit}{tail}}}{(i + 1 < ordered.Count ? "," : "")}");
                }

                _w.Outdent();
                _w.Line(");");
            }

            if (o.Map != null)
            {
                _w.Line($"static constexpr std::size_t keys = {ordered.FindIndex(m => m.WireName == "Keys")};");
                _w.Line($"static constexpr std::size_t values = {ordered.FindIndex(m => m.WireName == "Values")};");
            }

            _w.Close(";");
        }

        private void EmitTableAccessors(ObjectModel o)
        {
            var ordered = LayoutBuilder.WireOrder(o).ToList();
            _w.Line();
            foreach (var m in o.Members)
            {
                int index = ordered.IndexOf(m);
                _w.Line($"TESSERA_INLINE {AccessorType(m.Value)} {o.CppName}::{m.CppName}() const noexcept {{ return tessera_get<{index}>(); }}");
            }

            foreach (var m in o.Members)
            {
                int index = ordered.IndexOf(m);
                _w.Line($"TESSERA_INLINE bool {o.CppName}::{HasName(m)}() const noexcept {{ return tessera_has<{index}>(); }}");
            }
        }

        // ------------------------------------------------------------------ unions

        private void EmitUnionClass(UnionModel u)
        {
            _w.Line();
            _w.Line($"/// C# {Describe(u.Symbol)} {u.DisplayName} (union of {string.Join(", ", u.Members.Select(m => m.Type.DisplayName))})");
            _w.Line($"class {u.CppName} final : public tessera::UnionBase {{");
            _w.Line("public:");
            _w.Indent();
            _w.Line("using UnionBase::UnionBase;");
            _w.Line();
            _w.Line("enum class Tag : std::uint32_t {");
            _w.Indent();
            _w.Line("None = 0,");
            foreach (var m in u.Members) _w.Line($"{m.Type.CppName} = 0x{m.Tag:X8}u,");
            _w.Outdent();
            _w.Line("};");
            string typeName = _settings.Naming == CppNaming.PascalCase || _settings.Naming == CppNaming.Original ? "Type" : "type";
            _w.Line($"Tag {typeName}() const noexcept {{ return static_cast<Tag>(tag()); }}");
            foreach (var m in u.Members) _w.Line($"{Qualified(m.Type.Symbol, m.Type.CppName)} {AsName(m)}() const noexcept;");
            _w.Outdent();
            _w.Line("};");
        }

        private string AsName(UnionMember m)
        {
            string member = Naming.Member(m.Type.Symbol.Name, _settings.Naming);
            switch (_settings.Naming)
            {
                case CppNaming.CamelCase: return "as" + char.ToUpperInvariant(member[0]) + member.Substring(1);
                case CppNaming.PascalCase:
                case CppNaming.Original: return "As" + char.ToUpperInvariant(member[0]) + member.Substring(1);
                default: return "as_" + member;
            }
        }

        private void EmitUnionSchema(UnionModel u)
        {
            string q = Qualified(u.Symbol, u.CppName);
            _w.Line();
            _w.Open($"template <> struct schema<{q}>");
            _w.Line($"static constexpr std::string_view name = {CppString(u.DisplayName)};");
            _w.Line($"static constexpr std::uint64_t fingerprint = 0x{u.Fingerprint:X16}ull;");
            _w.Line($"static constexpr std::uint64_t deep_fingerprint = 0x{u.DeepFingerprint:X16}ull;");
            var members = u.Members.Select(m => $"member<{Qualified(m.Type.Symbol, m.Type.CppName)}>{{0x{m.Tag:X8}u}}");
            _w.Line($"static constexpr auto members = std::make_tuple({string.Join(", ", members)});");
            _w.Close(";");
        }

        private void EmitUnionAccessors(UnionModel u)
        {
            _w.Line();
            foreach (var m in u.Members)
            {
                string t = Qualified(m.Type.Symbol, m.Type.CppName);
                _w.Line($"TESSERA_INLINE {t} {u.CppName}::{AsName(m)}() const noexcept {{ return tessera_as<{t}>(0x{m.Tag:X8}u); }}");
            }
        }

        // ------------------------------------------------------------------ types

        private string FieldType(ValueModel v)
        {
            string t = ElementType(v);
            if (v.IsNullableValueType && (v.Kind != WireKind.SharedStruct)) return "std::optional<" + t + ">";
            return t;
        }

        /// <summary>C++ element type of a vector (or a dictionary key or value): nullable values are optional.</summary>
        private string VectorElementType(ValueModel e) => e.IsNullableValueType ? "std::optional<" + ElementType(e) + ">" : ElementType(e);

        /// <summary>Declared C++ type of a field or vector element (shared structs keep the tessera::shared marker).</summary>
        private string ElementType(ValueModel v)
        {
            switch (v.Kind)
            {
                case WireKind.String: return "std::string_view";
                case WireKind.Object: return v.Object!.Map != null ? MapSpelling(v.Object) : Qualified(v.Object.Symbol, v.Object.CppName);
                case WireKind.Union: return Qualified(v.Union!.Symbol, v.Union.CppName);
                case WireKind.Struct: return Qualified(v.Struct!.Symbol, v.Struct.CppName);
                case WireKind.SharedStruct: return "tessera::shared<" + Qualified(v.Struct!.Symbol, v.Struct.CppName) + ">";
                case WireKind.Vector: return "tessera::Vector<" + VectorElementType(v.Vector!.Element) + ">";
                default:
                    if (v.Enum != null) return Qualified(v.Enum.Symbol, v.Enum.CppName);
                    return ScalarType(v.Kind);
            }
        }

        /// <summary>Return type of an accessor. Inline structs without bool members are returned by reference into the buffer.</summary>
        private string AccessorType(ValueModel v)
        {
            bool byRef = (v.Kind == WireKind.Struct && !v.IsNullableValueType || v.Kind == WireKind.SharedStruct) && !HasBool(v.Struct!);
            if (v.Kind == WireKind.SharedStruct || v.Kind == WireKind.Struct && !v.IsNullableValueType)
            {
                string t = Qualified(v.Struct!.Symbol, v.Struct.CppName);
                return byRef ? "const " + t + "&" : t;
            }

            return FieldType(v);
        }

        private static bool HasBool(StructModel s) => s.Fields.Any(f => f.Kind == WireKind.Bool || f.Struct != null && HasBool(f.Struct));

        internal static string ScalarType(WireKind kind)
        {
            switch (kind)
            {
                case WireKind.Bool: return "bool";
                case WireKind.Int8: return "std::int8_t";
                case WireKind.UInt8: return "std::uint8_t";
                case WireKind.Int16: return "std::int16_t";
                case WireKind.UInt16: return "std::uint16_t";
                case WireKind.Char16: return "char16_t";
                case WireKind.Int32: return "std::int32_t";
                case WireKind.UInt32: return "std::uint32_t";
                case WireKind.Int64: return "std::int64_t";
                case WireKind.UInt64: return "std::uint64_t";
                case WireKind.Float32: return "float";
                case WireKind.Float64: return "double";
                default: return "void";
            }
        }

        private string DefaultLiteral(MemberModel m)
        {
            var v = m.Value;
            if (v.IsNullableValueType || !m.HasCustomDefault || m.DefaultValue == null) return "";
            object d = m.DefaultValue;
            if (v.Enum != null)
            {
                long raw = Convert.ToInt64(d, CultureInfo.InvariantCulture);
                foreach (var kv in v.Enum.Values)
                {
                    if (Convert.ToInt64(kv.Value, CultureInfo.InvariantCulture) == raw)
                    {
                        return Qualified(v.Enum.Symbol, v.Enum.CppName) + "::" + Naming.Sanitize(kv.Key);
                    }
                }

                return $"static_cast<{Qualified(v.Enum.Symbol, v.Enum.CppName)}>({EnumLiteral(v.Enum.Underlying, d)})";
            }

            switch (v.Kind)
            {
                case WireKind.Bool: return d is bool b && b ? "true" : "";
                case WireKind.Float32:
                {
                    float f = Convert.ToSingle(d, CultureInfo.InvariantCulture);
                    if (float.IsNaN(f)) return "std::numeric_limits<float>::quiet_NaN()";
                    if (float.IsInfinity(f)) return (f < 0 ? "-" : "") + "std::numeric_limits<float>::infinity()";
                    if (BitConverter.ToInt32(BitConverter.GetBytes(f), 0) == 0) return "";
                    return FloatLiteral(f.ToString("R", CultureInfo.InvariantCulture)) + "f";
                }
                case WireKind.Float64:
                {
                    double f = Convert.ToDouble(d, CultureInfo.InvariantCulture);
                    if (double.IsNaN(f)) return "std::numeric_limits<double>::quiet_NaN()";
                    if (double.IsInfinity(f)) return (f < 0 ? "-" : "") + "std::numeric_limits<double>::infinity()";
                    if (BitConverter.DoubleToInt64Bits(f) == 0) return "";
                    return FloatLiteral(f.ToString("R", CultureInfo.InvariantCulture));
                }
                case WireKind.Char16:
                    int c = Convert.ToInt32(d, CultureInfo.InvariantCulture);
                    return c == 0 ? "" : $"char16_t{{{c}}}";
                default:
                    long n = Convert.ToInt64(d is ulong u && u > long.MaxValue ? (object)(long)0 : d, CultureInfo.InvariantCulture);
                    if (d is ulong big && big > long.MaxValue) return big.ToString(CultureInfo.InvariantCulture) + "ull";
                    if (n == 0) return "";
                    return EnumLiteral(v.Kind, d);
            }
        }

        private static string FloatLiteral(string s)
        {
            s = s.Replace("E+", "e").Replace("E", "e");
            return s.IndexOf('.') >= 0 || s.IndexOf('e') >= 0 ? s : s + ".0";
        }

        private static string MemberComment(MemberModel m)
        {
            string text = m.CsTypeDisplay + " " + m.CsName;
            if (m.HasCustomDefault && m.DefaultValue != null)
            {
                string shown = Convert.ToString(m.DefaultValue is bool b ? (b ? "true" : "false") : m.DefaultValue, CultureInfo.InvariantCulture) ?? "";
                if (m.Value.Enum != null)
                {
                    long raw = Convert.ToInt64(m.DefaultValue, CultureInfo.InvariantCulture);
                    foreach (var kv in m.Value.Enum.Values)
                    {
                        if (Convert.ToInt64(kv.Value, CultureInfo.InvariantCulture) == raw)
                        {
                            shown = m.Value.Enum.Symbol.Name + "." + kv.Key;
                            break;
                        }
                    }
                }

                text += " = " + shown;
            }

            if (m.WireName != m.CsName) text += $" (wire name \"{m.WireName}\")";
            return text;
        }

        private static string Describe(INamedTypeSymbol s)
        {
            if (s.IsRecord) return s.IsValueType ? "record struct" : "record";
            if (s.TypeKind == TypeKind.Interface) return "interface";
            if (s.IsValueType) return "struct";
            return s.IsAbstract ? "abstract class" : "class";
        }

        private static string CppString(string s)
        {
            var sb = new System.Text.StringBuilder(s.Length + 2);
            sb.Append('"');
            foreach (byte b in System.Text.Encoding.UTF8.GetBytes(s))
            {
                if (b == '"' || b == '\\') sb.Append('\\').Append((char)b);
                else if (b < 32 || b >= 127) sb.Append("\\x").Append(b.ToString("x2")).Append("\"\"");
                else sb.Append((char)b);
            }

            return sb.Append('"').ToString();
        }
    }
}
