using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Tessera.Generator
{
    /// <summary>Emits the C# writer code, schema entries and registrations.</summary>
    internal sealed class CSharpEmitter
    {
        private readonly List<TypeModel> _types;
        private readonly string _ns;
        private readonly CodeWriter _w = new CodeWriter();
        private readonly Dictionary<string, string> _vectorHelpers = new Dictionary<string, string>();
        private readonly List<Action> _pendingHelpers = new List<Action>();
        private readonly List<string> _accessors = new List<string>();

        public CSharpEmitter(List<TypeModel> types, string generatedNamespace)
        {
            _types = types;
            _ns = generatedNamespace;
        }

        public string Emit()
        {
            _w.Line("// <auto-generated/>");
            _w.Line("// Generated by Tessera.Generator. Do not edit.");
            _w.Line("#nullable disable");
            _w.Line("#pragma warning disable CS1591, CS0618, CS0612, CA2255, CS8669");
            _w.Line("using global::System;");
            _w.Line("using global::System.Runtime.CompilerServices;");
            _w.Line("using global::Tessera;");
            _w.Line();
            _w.Open("namespace " + _ns);
            EmitSchema();
            _w.Line();
            EmitWriters();
            _w.Line();
            EmitRegistration();
            _w.Close();
            return _w.ToString();
        }

        // ------------------------------------------------------------------ schema

        private void EmitSchema()
        {
            _w.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            _w.Open("internal static class TesseraSchema");
            foreach (var t in _types)
            {
                string bytes = string.Join(", ", t.Entry.Select(b => "0x" + b.ToString("X2")));
                string slots = string.Join(", ", t.RefSlots);
                _w.Line($"public static readonly TesseraType T{t.Index} = new TesseraType({Naming.CsString(Display(t))}, 0x{t.Fingerprint:X16}UL, 0x{t.DeepFingerprint:X16}UL, new byte[] {{ {bytes} }}, new ushort[] {{ {slots} }});");
            }

            _w.Line();
            _w.Open("static TesseraSchema()");
            foreach (var t in _types)
            {
                if (t.References.Count == 0) continue;
                _w.Line($"T{t.Index}.SetReferences({string.Join(", ", t.References.Select(r => "T" + r.Index))});");
            }

            _w.Close();
            _w.Close();
        }

        private static string Display(TypeModel t)
        {
            switch (t)
            {
                case ObjectModel o: return o.DisplayName;
                case StructModel s: return s.DisplayName;
                case UnionModel u: return u.DisplayName;
                case VectorModel v: return "vector<" + ElementDisplay(v.Element) + ">";
                default: return t.Key;
            }
        }

        private static string ElementDisplay(ValueModel e)
        {
            switch (e.Kind)
            {
                case WireKind.Vector: return "vector<" + ElementDisplay(e.Vector!.Element) + ">";
                case WireKind.Object: return e.Object!.DisplayName;
                case WireKind.Union: return e.Union!.DisplayName;
                case WireKind.Struct:
                case WireKind.SharedStruct: return e.Struct!.DisplayName;
                default: return e.Enum?.DisplayName ?? e.Kind.ToString();
            }
        }

        // ------------------------------------------------------------------ writers

        private void EmitWriters()
        {
            _w.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            _w.Open("internal static class TesseraWriters");
            foreach (var t in _types)
            {
                switch (t)
                {
                    case ObjectModel o: EmitObject(o); break;
                    case StructModel s: EmitStruct(s); break;
                    case UnionModel u: EmitUnion(u); break;
                }
            }

            for (int i = 0; i < _pendingHelpers.Count; i++) _pendingHelpers[i]();
            foreach (var a in _accessors) _w.Line(a);
            _w.Close();
        }

        private static string In(ObjectModel o) => o.IsValueType ? "in " : "";

        private void EmitObject(ObjectModel o)
        {
            if (o.Map != null)
            {
                EmitMap(o);
                return;
            }

            _w.Line();
            _w.Line($"/// <summary>Writes {Xml(o.DisplayName)}.</summary>");
            _w.Open($"public static int Write{o.Index}(TesseraWriter w, {In(o)}{o.CsName} v)");
            _w.Line("w.Enter();");

            // 1. Children, last cell first so the first cell's child ends up at the lowest address.
            foreach (var m in Enumerable.Reverse(o.Cells))
            {
                var v = m.Value;
                string id = Id(m);
                switch (v.Kind)
                {
                    case WireKind.String:
                        _w.Line($"int r{id} = 0;");
                        _w.Line($"{{ var x = v.{m.CsName}; if (x is not null) r{id} = w.WriteString(x); }}");
                        break;
                    case WireKind.Vector:
                        _w.Line($"int r{id} = 0;");
                        _w.Line($"{{ var x = v.{m.CsName}; if (x is not null) r{id} = {VectorHelper(v)}(w, x); }}");
                        break;
                    case WireKind.Object:
                        _w.Line($"int r{id} = 0;");
                        if (v.Object!.IsValueType)
                        {
                            if (v.IsNullableValueType) _w.Line($"{{ var x = v.{m.CsName}; if (x.HasValue) r{id} = Write{v.Object.Index}(w, x.GetValueOrDefault()); }}");
                            else _w.Line($"r{id} = Write{v.Object.Index}(w, v.{m.CsName});");
                        }
                        else
                        {
                            _w.Line($"{{ var x = v.{m.CsName}; if (x is not null) r{id} = Write{v.Object.Index}(w, x); }}");
                        }

                        break;
                    case WireKind.Union:
                        _w.Line($"int r{id} = 0; uint t{id} = 0;");
                        _w.Line($"{{ var x = v.{m.CsName}; if (x is not null) r{id} = Union{v.Union!.Index}(w, x, out t{id}); }}");
                        break;
                    case WireKind.SharedStruct:
                        _w.Line($"int r{id} = 0;");
                        if (v.IsNullableValueType)
                        {
                            _w.Line($"{{ var x = v.{m.CsName}; if (x.HasValue) {{ var y = x.GetValueOrDefault(); r{id} = Shared{v.Struct!.Index}(w, in y); }} }}");
                        }
                        else
                        {
                            _w.Line($"{{ var x = v.{m.CsName}; if ({KeepOrDefault(m)} || !IsDefault{v.Struct!.Index}(in x)) r{id} = Shared{v.Struct.Index}(w, in x); }}");
                        }

                        break;
                }
            }

            // 2. Inline values and presence (fixed cells are always stored).
            foreach (var m in LayoutBuilder.WireOrder(o))
            {
                var v = m.Value;
                string id = Id(m);
                if (WireFormat.IsReference(v.Kind)) continue;
                _w.Line($"var s{id} = v.{m.CsName};");
                if (v.IsNullableValueType || m.IsFixed) continue;
                if (v.Kind == WireKind.Bool) continue;
                if (v.Kind == WireKind.Struct)
                {
                    _w.Line($"bool p{id} = {KeepOrDefault(m)} || !IsDefault{v.Struct!.Index}(in s{id});");
                }
                else
                {
                    _w.Line($"bool p{id} = {KeepOrDefault(m)} || {NotDefault("s" + id, m)};");
                }
            }

            int words = o.HeaderWords;
            for (int i = 0; i < words; i++) _w.Line($"uint h{i} = 0;");
            _w.Line("int cells = 0;");
            ulong a8Mask = 0;
            bool hasA8 = false;
            foreach (var m in o.Cells)
            {
                _w.Line($"if ({Present(m)}) {{ h{m.Bit / 32} |= 0x{1u << (m.Bit % 32):X}u; cells += {m.CellSize}; }}");
                if (m.CellAlign == 8)
                {
                    hasA8 = true;
                    if (m.Bit < 64) a8Mask |= 1UL << m.Bit;
                }
            }

            foreach (var m in o.Bools)
            {
                string id = Id(m);
                string val = m.Value.IsNullableValueType ? $"s{id}.GetValueOrDefault()" : $"s{id}";
                string present = m.Value.IsNullableValueType ? $"s{id}.HasValue" : (m.KeepDefault ? "true" : $"w.WriteDefaults || s{id} != {BoolLiteral(m)}");
                int pb = m.Bit, vb = m.Bit + 1;
                _w.Line($"if ({present}) {{ h{pb / 32} |= 0x{1u << (pb % 32):X}u; if ({val}) h{vb / 32} |= 0x{1u << (vb % 32):X}u; }}");
            }

            string align = "4";
            if (o.Fixed.Any(m => m.CellAlign == 8))
            {
                align = "8";
            }
            else if (hasA8)
            {
                var parts = new List<string>();
                foreach (var m in o.Cells.Where(c => c.CellAlign == 8)) parts.Add($"(h{m.Bit / 32} & 0x{1u << (m.Bit % 32):X}u) != 0");
                align = "(" + string.Join(" || ", parts) + ") ? 8 : 4";
            }

            int start = 4 * words + o.FixedSize; // the first optional cell
            _w.Line($"int size = {start} + cells;");
            _w.Line(o.FixedSize > 0 ? $"ref byte o = ref w.BeginObject(size, {o.FixedSize} + cells, {align});" : $"ref byte o = ref w.BeginObject(size, cells, {align});");
            _w.Line("int at = w.Position;");
            for (int i = 0; i < words; i++) _w.Line(i == 0 ? "Unsafe.WriteUnaligned(ref o, h0);" : $"Unsafe.WriteUnaligned(ref Unsafe.Add(ref o, {4 * i}), h{i});");
            int fixedEnd = 0;
            foreach (var m in o.Fixed)
            {
                string id = Id(m);
                string fixedAt = $"ref Unsafe.Add(ref o, {4 * words + m.FixedOffset})";
                if (m.Value.Kind == WireKind.Struct) _w.Line($"Struct{m.Value.Struct!.Index}({fixedAt}, in s{id});");
                else _w.Line($"Unsafe.WriteUnaligned({fixedAt}, {ScalarCast(m.Value, "s" + id)});");
                fixedEnd = m.FixedOffset + m.CellSize;
            }

            if (o.FixedSize > fixedEnd) _w.Line($"Unsafe.InitBlockUnaligned(ref Unsafe.Add(ref o, {4 * words + fixedEnd}), 0, {o.FixedSize - fixedEnd});");
            if (o.Cells.Count > 0) _w.Line($"int c = {start};");
            if (o.RefCellCount > 0)
            {
                _w.Line($"Span<int> refs = stackalloc int[{o.RefCellCount}];");
                _w.Line("int nr = 0;");
            }

            foreach (var m in o.Cells)
            {
                var v = m.Value;
                string id = Id(m);
                string at = "ref Unsafe.Add(ref o, c)";
                switch (v.Kind)
                {
                    case WireKind.String:
                    case WireKind.Vector:
                    case WireKind.Object:
                    case WireKind.SharedStruct:
                        _w.Line($"if (r{id} != 0) {{ TesseraWriter.WriteOffset({at}, at - c, r{id}); refs[nr++] = c; c += 4; }}");
                        break;
                    case WireKind.Union:
                        _w.Line($"if (r{id} != 0) {{ Unsafe.WriteUnaligned({at}, t{id}); TesseraWriter.WriteOffset(ref Unsafe.Add(ref o, c + 4), at - c - 4, r{id}); refs[nr++] = c + 4; c += 8; }}");
                        break;
                    case WireKind.Struct:
                        if (v.IsNullableValueType) _w.Line($"if (s{id}.HasValue) {{ var y = s{id}.GetValueOrDefault(); Struct{v.Struct!.Index}({at}, in y); c += {m.CellSize}; }}");
                        else _w.Line($"if (p{id}) {{ Struct{v.Struct!.Index}({at}, in s{id}); c += {m.CellSize}; }}");
                        break;
                    default:
                        string expr = v.IsNullableValueType ? $"s{id}.GetValueOrDefault()" : "s" + id;
                        _w.Line($"if ({Present(m)}) {{ Unsafe.WriteUnaligned({at}, {ScalarCast(v, expr)}); c += {m.CellSize}; }}");
                        break;
                }
            }

            string refsArg = o.RefCellCount > 0 ? "refs.Slice(0, nr)" : "default";
            _w.Line($"int pos = w.EndObject(TesseraSchema.T{o.Index}, size, {refsArg});");
            _w.Line("w.Exit();");
            _w.Line("return pos;");
            _w.Close();
        }

        /// <summary>A dictionary: its entries sorted by key, then the values and keys vectors and a two-cell object.</summary>
        private void EmitMap(ObjectModel o)
        {
            var map = o.Map!;
            string kvp = "global::System.Collections.Generic.KeyValuePair<" + map.CsKeyType + ", " + map.CsValueType + ">";
            string keyPool = "global::System.Buffers.ArrayPool<" + map.CsKeyType + ">.Shared";
            string valuePool = "global::System.Buffers.ArrayPool<" + map.CsValueType + ">.Shared";
            var keys = o.Members.Single(m => m.WireName == "Keys");
            var values = o.Members.Single(m => m.WireName == "Values");
            _w.Line();
            _w.Line($"/// <summary>Writes {Xml(o.DisplayName)}: keys ascending, values in key order.</summary>");
            _w.Open($"public static int Write{o.Index}(TesseraWriter w, {o.CsName} v)");
            _w.Line("w.Enter();");
            _w.Line($"int n = v is global::System.Collections.Generic.ICollection<{kvp}> c ? c.Count : global::System.Linq.Enumerable.Count(v);");
            _w.Line($"{map.CsKeyType}[] keys = {keyPool}.Rent(n);");
            _w.Line($"{map.CsValueType}[] values = {valuePool}.Rent(n);");
            _w.Line("int count = 0;");
            // A Dictionary is enumerated with its own struct enumerator: no boxing, no interface calls per entry.
            _w.Open($"if (v is global::System.Collections.Generic.Dictionary<{map.CsKeyType}, {map.CsValueType}> d)");
            _w.Open("foreach (var kv in d)");
            _w.Line("if (count == n) break;");
            _w.Line("keys[count] = kv.Key;");
            _w.Line("values[count++] = kv.Value;");
            _w.Close();
            _w.Close();
            _w.Open("else");
            _w.Open("foreach (var kv in v)");
            _w.Line("if (count == n) break;");
            _w.Line("keys[count] = kv.Key;");
            _w.Line("values[count++] = kv.Value;");
            _w.Close();
            _w.Close();
            // Strings by code point: the order of their UTF-8 bytes, which is how C++ compares them.
            _w.Line(map.Key.Kind == WireKind.String ? "TesseraMapKeys.SortUtf8(keys, values, count);" : "TesseraMapKeys.Sort(keys, values, count);");
            _w.Line($"int rValues = {VectorHelper(values.Value)}(w, new global::System.ReadOnlySpan<{map.CsValueType}>(values, 0, count));");
            _w.Line($"int rKeys = {VectorHelper(keys.Value)}(w, new global::System.ReadOnlySpan<{map.CsKeyType}>(keys, 0, count));");
            _w.Line($"{keyPool}.Return(keys, clearArray: {(map.Key.IsReferenceType ? "true" : "false")});");
            _w.Line($"{valuePool}.Return(values, clearArray: {(map.Value.IsReferenceType ? "true" : "false")});");
            // Both cells are always present (an empty dictionary has empty vectors).
            _w.Line("ref byte o = ref w.BeginObject(12, 8, 4);");
            _w.Line("int at = w.Position;");
            _w.Line($"Unsafe.WriteUnaligned(ref o, 0x{(1u << o.Cells[0].Bit) | (1u << o.Cells[1].Bit):X}u);");
            _w.Line("Span<int> refs = stackalloc int[2];");
            for (int i = 0; i < 2; i++)
            {
                int c = 4 + 4 * i;
                string r = o.Cells[i].WireName == "Keys" ? "rKeys" : "rValues";
                _w.Line($"TesseraWriter.WriteOffset(ref Unsafe.Add(ref o, {c}), at - {c}, {r});");
                _w.Line($"refs[{i}] = {c};");
            }

            _w.Line($"int pos = w.EndObject(TesseraSchema.T{o.Index}, 12, refs);");
            _w.Line("w.Exit();");
            _w.Line("return pos;");
            _w.Close();
        }

        private static string Id(MemberModel m) => "_" + Naming.CsIdentifier(m.CsName);

        private static string KeepOrDefault(MemberModel m) => m.KeepDefault ? "true" : "w.WriteDefaults";

        private static string Present(MemberModel m)
        {
            string id = Id(m);
            var v = m.Value;
            if (WireFormat.IsReference(v.Kind)) return $"r{id} != 0";
            if (v.IsNullableValueType) return $"s{id}.HasValue";
            return "p" + id;
        }

        private static string BoolLiteral(MemberModel m) => m.DefaultValue is bool b && b ? "true" : "false";

        private static string NotDefault(string expr, MemberModel m)
        {
            var v = m.Value;
            object? d = m.DefaultValue;
            switch (v.Kind)
            {
                case WireKind.Float32:
                {
                    float f = d == null ? 0f : Convert.ToSingle(d, CultureInfo.InvariantCulture);
                    int bits = BitConverter.ToInt32(BitConverter.GetBytes(f), 0);
                    return $"BitConverter.SingleToInt32Bits({expr}) != {bits}";
                }
                case WireKind.Float64:
                {
                    double f = d == null ? 0d : Convert.ToDouble(d, CultureInfo.InvariantCulture);
                    long bits = BitConverter.DoubleToInt64Bits(f);
                    return $"BitConverter.DoubleToInt64Bits({expr}) != {bits}L";
                }
                case WireKind.Char16:
                    return $"{expr} != (char){(d == null ? 0 : Convert.ToInt32(d, CultureInfo.InvariantCulture))}";
            }

            string literal = IntegerLiteral(v.Kind, d);
            if (v.Enum != null) return $"({v.Enum.UnderlyingCs}){expr} != {literal}";
            return $"{expr} != {literal}";
        }

        internal static string IntegerLiteral(WireKind kind, object? d)
        {
            if (d == null) return "0";
            switch (kind)
            {
                case WireKind.UInt64: return Convert.ToUInt64(d, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture) + "UL";
                case WireKind.Int64: return "(" + Convert.ToInt64(d, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture) + "L)";
                case WireKind.UInt32: return Convert.ToUInt32(d, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture) + "U";
                default: return "(" + Convert.ToInt64(d, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture) + ")";
            }
        }

        private static string ScalarCast(ValueModel v, string expr)
        {
            if (v.Enum != null) return $"({v.Enum.UnderlyingCs}){expr}";
            if (v.Kind == WireKind.Char16) return $"(ushort){expr}";
            return expr;
        }

        // ------------------------------------------------------------------ structs

        private void EmitStruct(StructModel s)
        {
            _w.Line();
            _w.Open($"public static void Struct{s.Index}(ref byte d, in {s.CsName} v)");
            if (s.External)
            {
                // Non-public fields of types from other assemblies are invisible to the generator. SizeOf is a JIT
                // constant, so this costs nothing when the layout matches.
                string message = $"Struct {s.DisplayName} comes from another assembly and has fields Tessera cannot see " +
                                 $"(its public fields take {s.Size} bytes). Make its fields public or declare the struct in this project.";
                _w.Line($"if (Unsafe.SizeOf<{s.CsName}>() != {s.Size}) throw new TesseraException({Naming.CsString(message)});");
            }

            int cursor = 0;
            foreach (var f in s.Fields)
            {
                if (f.Offset > cursor) _w.Line($"Unsafe.InitBlockUnaligned(ref Unsafe.Add(ref d, {cursor}), 0, {f.Offset - cursor});");
                string value = FieldRead(s, f);
                string dst = f.Offset == 0 ? "ref d" : $"ref Unsafe.Add(ref d, {f.Offset})";
                if (f.Struct != null) _w.Line($"Struct{f.Struct.Index}({dst}, {value});");
                else if (f.Kind == WireKind.Bool) _w.Line($"Unsafe.Add(ref d, {f.Offset}) = {value} ? (byte)1 : (byte)0;");
                else if (f.Enum != null) _w.Line($"Unsafe.WriteUnaligned({dst}, ({f.Enum.UnderlyingCs}){value});");
                else if (f.Kind == WireKind.Char16) _w.Line($"Unsafe.WriteUnaligned({dst}, (ushort){value});");
                else _w.Line($"Unsafe.WriteUnaligned({dst}, {value});");
                cursor = f.Offset + f.Size;
            }

            if (s.Size > cursor) _w.Line($"Unsafe.InitBlockUnaligned(ref Unsafe.Add(ref d, {cursor}), 0, {s.Size - cursor});");
            _w.Close();

            var conditions = new List<string>();
            foreach (var f in s.Fields)
            {
                string value = FieldRead(s, f);
                if (f.Struct != null) conditions.Add($"IsDefault{f.Struct.Index}({value})");
                else if (f.Kind == WireKind.Bool) conditions.Add($"!{value}");
                else if (f.Kind == WireKind.Float32) conditions.Add($"BitConverter.SingleToInt32Bits({value}) == 0");
                else if (f.Kind == WireKind.Float64) conditions.Add($"BitConverter.DoubleToInt64Bits({value}) == 0");
                else if (f.Enum != null) conditions.Add($"({f.Enum.UnderlyingCs}){value} == 0");
                else if (f.Kind == WireKind.Char16) conditions.Add($"{value} == '\\0'");
                else conditions.Add($"{value} == 0");
            }

            _w.Line($"public static bool IsDefault{s.Index}(in {s.CsName} v) => {string.Join(" && ", conditions)};");
            _w.Open($"public static int Shared{s.Index}(TesseraWriter w, in {s.CsName} v)");
            _w.Line($"Struct{s.Index}(ref w.BeginShared({s.Size}, {s.Align}), in v);");
            _w.Line($"return w.EndShared({s.Size}, {s.Align});");
            _w.Close();
        }

        private string FieldRead(StructModel s, StructField f)
        {
            if (f.PrivateAccessor == null) return "v" + f.Access;
            if (!_accessors.Any(a => a.Contains(" " + f.PrivateAccessor + "(")))
            {
                _accessors.Add($"[UnsafeAccessor(UnsafeAccessorKind.Field, Name = {Naming.CsString(f.Access)})] private static extern ref {f.CsType} {f.PrivateAccessor}(ref {s.CsName} owner);");
            }

            return $"{f.PrivateAccessor}(ref Unsafe.AsRef(in v))";
        }

        // ------------------------------------------------------------------ unions

        private void EmitUnion(UnionModel u)
        {
            _w.Line();
            _w.Open($"public static int Union{u.Index}(TesseraWriter w, {u.CsName} v, out uint tag)");
            _w.Open("switch (v)");
            foreach (var m in u.Members.OrderByDescending(x => x.Depth).ThenBy(x => x.Tag))
            {
                string arg = m.Type.IsValueType ? "in x" : "x";
                _w.Line($"case {m.Type.CsName} x: tag = 0x{m.Tag:X8}u; w.MarkUsed(TesseraSchema.T{m.Type.Index}); return Write{m.Type.Index}(w, {arg});");
            }

            _w.Line($"default: throw new TesseraException(\"Type \" + v.GetType() + \" is not a member of union {u.DisplayName}.\");");
            _w.Close();
            _w.Close();
        }

        // ------------------------------------------------------------------ vectors

        private string VectorHelper(ValueModel collection)
        {
            // The same C# collection type can hold different wire vectors (e.g. List<Item> restricted by [TesseraUnion]).
            string key = collection.CsType + "|" + collection.Vector!.Key;
            if (_vectorHelpers.TryGetValue(key, out var name)) return name;
            name = "Vector" + collection.Vector!.Index + "_" + _vectorHelpers.Count;
            _vectorHelpers[key] = name;
            string helperName = name;
            _pendingHelpers.Add(() => EmitVector(helperName, collection));
            return name;
        }

        private void EmitVector(string name, ValueModel collection)
        {
            var e = collection.Vector!.Element;
            _w.Line();
            _w.Open($"public static int {name}(TesseraWriter w, {collection.CsType} v)");
            string count = collection.Shape == CollectionShape.Array || collection.Shape == CollectionShape.Span ? "v.Length" : "v.Count";
            if (collection.Shape == CollectionShape.Enumerable)
            {
                _w.Line($"var list = new global::System.Collections.Generic.List<{e.CsTypeWithNullable()}>(v);");
                _w.Line("return " + VectorHelper(ListOf(collection, e)) + "(w, list);");
                _w.Close();
                return;
            }

            string span = collection.Shape == CollectionShape.Array || collection.Shape == CollectionShape.Span ? "v" : collection.Shape == CollectionShape.List ? "TesseraWriter.AsSpan(v)" : null!;
            if (e.IsNullableValueType)
            {
                // Optional values: a presence bit per element, then every element's value (zero when absent).
                int size = e.Kind == WireKind.Struct ? e.Struct!.Size : Math.Max(1, WireFormat.CellSize(e.Kind));
                int align = e.Kind == WireKind.Struct ? e.Struct!.Align : size;
                _w.Line("w.EnterLeaf();");
                _w.Line($"int n = {count};");
                _w.Line($"ref byte d = ref w.BeginOptionalVector(n, {size}, {align});");
                _w.Line("int values = 4 * ((n + 31) >> 5);");
                if (span != null) _w.Line($"var items = {span};");
                _w.Open("for (int i = 0; i < n; i++)");
                _w.Line($"var x = {(span != null ? "items[i]" : "v[i]")};");
                _w.Line("if (!x.HasValue) continue;");
                _w.Line("ref byte bits = ref Unsafe.Add(ref d, 4 * (i >> 5));");
                _w.Line("Unsafe.WriteUnaligned(ref bits, Unsafe.ReadUnaligned<uint>(ref bits) | (1u << (i & 31)));");
                if (e.Kind == WireKind.Struct)
                {
                    _w.Line("var y = x.GetValueOrDefault();");
                    _w.Line($"Struct{e.Struct!.Index}(ref Unsafe.Add(ref d, values + i * {size}), in y);");
                }
                else if (e.Kind == WireKind.Bool) _w.Line("Unsafe.Add(ref d, values + i) = x.GetValueOrDefault() ? (byte)1 : (byte)0;");
                else _w.Line($"Unsafe.WriteUnaligned(ref Unsafe.Add(ref d, values + i * {size}), {ScalarCast(e, "x.GetValueOrDefault()")});");
                _w.Close();
                _w.Line($"return w.EndOptionalVector(n, {size}, {align});");
                _w.Close();
                return;
            }

            bool scalar = e.Kind != WireKind.Bool && !WireFormat.IsReference(e.Kind) && e.Kind != WireKind.Struct;
            bool leaf = scalar || e.Kind == WireKind.Bool || e.Kind == WireKind.Struct;
            // A vector is one nesting level (as the C++ verifier counts it); a leaf vector only needs the check.
            _w.Line(leaf ? "w.EnterLeaf();" : "w.Enter();");
            if (scalar && span != null)
            {
                _w.Line($"return w.WriteScalars<{e.CsType}>({span});");
            }
            else if (e.Kind == WireKind.Bool && span != null)
            {
                _w.Line($"return w.WriteBools({span});");
            }
            else if (leaf)
            {
                int size = e.Kind == WireKind.Struct ? e.Struct!.Size : Math.Max(1, WireFormat.CellSize(e.Kind));
                int align = e.Kind == WireKind.Struct ? e.Struct!.Align : size;
                _w.Line($"int n = {count};");
                _w.Line($"ref byte d = ref w.BeginVector(n, {size}, {align});");
                if (span != null) _w.Line($"var items = {span};");
                string item = span != null ? "items[i]" : "v[i]";
                _w.Open("for (int i = 0; i < n; i++)");
                if (e.Kind == WireKind.Struct)
                {
                    _w.Line($"var x = {item};");
                    _w.Line($"Struct{e.Struct!.Index}(ref Unsafe.Add(ref d, i * {size}), in x);");
                }
                else if (e.Kind == WireKind.Bool) _w.Line($"Unsafe.Add(ref d, i) = {item} ? (byte)1 : (byte)0;");
                else _w.Line($"Unsafe.WriteUnaligned(ref Unsafe.Add(ref d, i * {size}), {ScalarCast(e, item)});");
                _w.Close();
                _w.Line($"return w.EndVector(n, {size}, {align});");
            }
            else
            {
                _w.Line($"int n = {count};");
                _w.Line("int slot = w.PushRefs(n);");
                bool union = e.Kind == WireKind.Union;
                if (union) _w.Line("uint[] tags = global::System.Buffers.ArrayPool<uint>.Shared.Rent(Math.Max(1, n));");
                _w.Open("for (int i = n - 1; i >= 0; i--)");
                _w.Line("var x = v[i];");
                switch (e.Kind)
                {
                    case WireKind.String:
                        _w.Line("w.SetRef(slot + i, x is null ? 0 : w.WriteString(x));");
                        break;
                    case WireKind.Object:
                        if (e.Object!.IsValueType) _w.Line($"w.SetRef(slot + i, Write{e.Object.Index}(w, in x));");
                        else _w.Line($"w.SetRef(slot + i, x is null ? 0 : Write{e.Object.Index}(w, x));");
                        break;
                    case WireKind.Vector:
                        _w.Line($"w.SetRef(slot + i, x is null ? 0 : {VectorHelper(e)}(w, x));");
                        break;
                    case WireKind.SharedStruct:
                        _w.Line($"w.SetRef(slot + i, Shared{e.Struct!.Index}(w, in x));");
                        break;
                    case WireKind.Union:
                        _w.Line($"uint tag = 0; w.SetRef(slot + i, x is null ? 0 : Union{e.Union!.Index}(w, x, out tag)); tags[i] = tag;");
                        break;
                }

                _w.Close();
                _w.Line("w.Exit();");
                if (union)
                {
                    _w.Line("int pos = w.WriteUnionVector(slot, n, tags.AsSpan(0, n));");
                    _w.Line("global::System.Buffers.ArrayPool<uint>.Shared.Return(tags);");
                    _w.Line("return pos;");
                }
                else
                {
                    _w.Line("return w.WriteRefVector(slot, n);");
                }
            }

            _w.Close();
        }

        private static ValueModel ListOf(ValueModel collection, ValueModel element) => new ValueModel
        {
            Kind = WireKind.Vector,
            Vector = collection.Vector,
            Shape = CollectionShape.List,
            CsType = "global::System.Collections.Generic.List<" + element.CsTypeWithNullable() + ">",
            Type = collection.Type,
            IsReferenceType = true,
        };

        // ------------------------------------------------------------------ registration

        private void EmitRegistration()
        {
            _w.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            _w.Open("internal static class TesseraRegistration");
            _w.Line("[ModuleInitializer]");
            _w.Open("internal static void Register()");
            foreach (var o in _types.OfType<ObjectModel>())
            {
                if (o.Map != null || o.Symbol.IsAbstract) continue;
                string writer = o.IsValueType ? $"static (w, x) => TesseraWriters.Write{o.Index}(w, in x)" : $"TesseraWriters.Write{o.Index}";
                _w.Line($"TesseraModel<{o.CsName}>.Register({writer}, TesseraSchema.T{o.Index});");
            }

            _w.Close();
            _w.Close();
        }

        private static string Xml(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }

    internal static class ValueModelExtensions
    {
        /// <summary>Element type as written in a generic argument (keeps Nullable&lt;T&gt;).</summary>
        public static string CsTypeWithNullable(this ValueModel v) => v.IsNullableValueType ? v.CsType + "?" : v.CsType;
    }
}
